True
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
PULL-UP
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
PULL-DOWN
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
Constructor pass
True
True
True
True
True
Exception
Exception
Exception
