True
True
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
<class 'Pin'>
PULL-UP
1
1
1
1
1
0
0
1
1
0
0
0
0
1
1
1
1
1
0
0
1
0
0
0
1
1
0
1
1
1
1
1
1
1
PULL-DOWN
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
Constructor pass
True
True
True
True
False
Exception
Exception
Exception
