#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := factory_fw

PROJECT_VER = "0.0.1"

include $(IDF_PATH)/make/project.mk

